// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.32.0
// source: api/group/group.proto

package grouppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 成员角色枚举
type Role int32

const (
	Role_ROLE_UNSPECIFIED Role = 0
	Role_ROLE_MEMBER      Role = 1
	Role_ROLE_ADMIN       Role = 2
	Role_ROLE_OWNER       Role = 3
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "ROLE_UNSPECIFIED",
		1: "ROLE_MEMBER",
		2: "ROLE_ADMIN",
		3: "ROLE_OWNER",
	}
	Role_value = map[string]int32{
		"ROLE_UNSPECIFIED": 0,
		"ROLE_MEMBER":      1,
		"ROLE_ADMIN":       2,
		"ROLE_OWNER":       3,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_api_group_group_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_api_group_group_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{0}
}

// 请求：获取群组成员
type ListGroupMembersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 群组 ID（UUID 格式，建议用 string 传输）
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersRequest) Reset() {
	*x = ListGroupMembersRequest{}
	mi := &file_api_group_group_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersRequest) ProtoMessage() {}

func (x *ListGroupMembersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersRequest.ProtoReflect.Descriptor instead.
func (*ListGroupMembersRequest) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{0}
}

func (x *ListGroupMembersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// 请求：获取群组信息
type ListGroupInfosRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       []string               `protobuf:"bytes,1,rep,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupInfosRequest) Reset() {
	*x = ListGroupInfosRequest{}
	mi := &file_api_group_group_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupInfosRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupInfosRequest) ProtoMessage() {}

func (x *ListGroupInfosRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupInfosRequest.ProtoReflect.Descriptor instead.
func (*ListGroupInfosRequest) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{1}
}

func (x *ListGroupInfosRequest) GetGroupId() []string {
	if x != nil {
		return x.GroupId
	}
	return nil
}

// 群成员信息
type GroupMember struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	Role          Role                   `protobuf:"varint,2,opt,name=role,proto3,enum=group.Role" json:"role,omitempty"`   // 成员角色
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`            //用户群中昵称
	JoinTime      string                 `protobuf:"bytes,4,opt,name=join_time,json=joinTime,proto3" json:"join_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupMember) Reset() {
	*x = GroupMember{}
	mi := &file_api_group_group_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupMember) ProtoMessage() {}

func (x *GroupMember) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupMember.ProtoReflect.Descriptor instead.
func (*GroupMember) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{2}
}

func (x *GroupMember) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GroupMember) GetRole() Role {
	if x != nil {
		return x.Role
	}
	return Role_ROLE_UNSPECIFIED
}

func (x *GroupMember) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *GroupMember) GetJoinTime() string {
	if x != nil {
		return x.JoinTime
	}
	return ""
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_api_group_group_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{3}
}

func (x *GroupInfo) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupInfo) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *GroupInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

// 响应：群组成员列表
type ListGroupMembersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"` // 群组 ID
	Members       []*GroupMember         `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`                // 成员列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupMembersResponse) Reset() {
	*x = ListGroupMembersResponse{}
	mi := &file_api_group_group_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupMembersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupMembersResponse) ProtoMessage() {}

func (x *ListGroupMembersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupMembersResponse.ProtoReflect.Descriptor instead.
func (*ListGroupMembersResponse) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{4}
}

func (x *ListGroupMembersResponse) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *ListGroupMembersResponse) GetMembers() []*GroupMember {
	if x != nil {
		return x.Members
	}
	return nil
}

type ListGroupInfosResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*GroupInfo           `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupInfosResponse) Reset() {
	*x = ListGroupInfosResponse{}
	mi := &file_api_group_group_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupInfosResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupInfosResponse) ProtoMessage() {}

func (x *ListGroupInfosResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_group_group_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupInfosResponse.ProtoReflect.Descriptor instead.
func (*ListGroupInfosResponse) Descriptor() ([]byte, []int) {
	return file_api_group_group_proto_rawDescGZIP(), []int{5}
}

func (x *ListGroupInfosResponse) GetGroups() []*GroupInfo {
	if x != nil {
		return x.Groups
	}
	return nil
}

var File_api_group_group_proto protoreflect.FileDescriptor

const file_api_group_group_proto_rawDesc = "" +
	"\n" +
	"\x15api/group/group.proto\x12\x05group\"4\n" +
	"\x17ListGroupMembersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"2\n" +
	"\x15ListGroupInfosRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x03(\tR\agroupId\"\x80\x01\n" +
	"\vGroupMember\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\x04role\x18\x02 \x01(\x0e2\v.group.RoleR\x04role\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x1b\n" +
	"\tjoin_time\x18\x04 \x01(\tR\bjoinTime\"]\n" +
	"\tGroupInfo\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\"c\n" +
	"\x18ListGroupMembersResponse\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12,\n" +
	"\amembers\x18\x02 \x03(\v2\x12.group.GroupMemberR\amembers\"B\n" +
	"\x16ListGroupInfosResponse\x12(\n" +
	"\x06groups\x18\x01 \x03(\v2\x10.group.GroupInfoR\x06groups*M\n" +
	"\x04Role\x12\x14\n" +
	"\x10ROLE_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vROLE_MEMBER\x10\x01\x12\x0e\n" +
	"\n" +
	"ROLE_ADMIN\x10\x02\x12\x0e\n" +
	"\n" +
	"ROLE_OWNER\x10\x032\xb2\x01\n" +
	"\fGroupService\x12S\n" +
	"\x10ListGroupMembers\x12\x1e.group.ListGroupMembersRequest\x1a\x1f.group.ListGroupMembersResponse\x12M\n" +
	"\x0eListGroupInfos\x12\x1c.group.ListGroupInfosRequest\x1a\x1d.group.ListGroupInfosResponseB1Z/github.com/AdventureDe/LinkIM/api/group;grouppbb\x06proto3"

var (
	file_api_group_group_proto_rawDescOnce sync.Once
	file_api_group_group_proto_rawDescData []byte
)

func file_api_group_group_proto_rawDescGZIP() []byte {
	file_api_group_group_proto_rawDescOnce.Do(func() {
		file_api_group_group_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_group_group_proto_rawDesc), len(file_api_group_group_proto_rawDesc)))
	})
	return file_api_group_group_proto_rawDescData
}

var file_api_group_group_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_group_group_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_group_group_proto_goTypes = []any{
	(Role)(0),                        // 0: group.Role
	(*ListGroupMembersRequest)(nil),  // 1: group.ListGroupMembersRequest
	(*ListGroupInfosRequest)(nil),    // 2: group.ListGroupInfosRequest
	(*GroupMember)(nil),              // 3: group.GroupMember
	(*GroupInfo)(nil),                // 4: group.GroupInfo
	(*ListGroupMembersResponse)(nil), // 5: group.ListGroupMembersResponse
	(*ListGroupInfosResponse)(nil),   // 6: group.ListGroupInfosResponse
}
var file_api_group_group_proto_depIdxs = []int32{
	0, // 0: group.GroupMember.role:type_name -> group.Role
	3, // 1: group.ListGroupMembersResponse.members:type_name -> group.GroupMember
	4, // 2: group.ListGroupInfosResponse.groups:type_name -> group.GroupInfo
	1, // 3: group.GroupService.ListGroupMembers:input_type -> group.ListGroupMembersRequest
	2, // 4: group.GroupService.ListGroupInfos:input_type -> group.ListGroupInfosRequest
	5, // 5: group.GroupService.ListGroupMembers:output_type -> group.ListGroupMembersResponse
	6, // 6: group.GroupService.ListGroupInfos:output_type -> group.ListGroupInfosResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_group_group_proto_init() }
func file_api_group_group_proto_init() {
	if File_api_group_group_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_group_group_proto_rawDesc), len(file_api_group_group_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_group_group_proto_goTypes,
		DependencyIndexes: file_api_group_group_proto_depIdxs,
		EnumInfos:         file_api_group_group_proto_enumTypes,
		MessageInfos:      file_api_group_group_proto_msgTypes,
	}.Build()
	File_api_group_group_proto = out.File
	file_api_group_group_proto_goTypes = nil
	file_api_group_group_proto_depIdxs = nil
}
